import type { Metadata } from 'next'
import './globals.css'
import cn from '@/utils/cn'
import { inter } from '@/app/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-neutral-950 text-white', inter.className)}>
        {children}
      </body>
    </html>
  )
}
